# ------------------------------------------------------------------
# db_post.R — Couche d'accès PostgreSQL (remplace db.R)
# ------------------------------------------------------------------
# Mêmes fonctions exportées que db.R (db_connect, db_init, db_touch,
# db_version, get_*, add_transaction), plus deux wrappers dbx_exec /
# dbx_get qui traduisent les placeholders '?' (style SQLite) en
# '$1, $2, ...' (style RPostgres). Les modules peuvent donc garder
# leurs requêtes telles quelles, à trois exceptions près (voir le
# message d'accompagnement).
#
# Connexion : lit DATABASE_URL (fournie par Railway), sinon les
# variables PGHOST / PGPORT / PGDATABASE / PGUSER / PGPASSWORD
# (pratiques pour le développement local).
#
# Dépendances : RPostgres, pool (à la place de RSQLite).
# ------------------------------------------------------------------

DB_TZ <- "Europe/Brussels"

# Le conteneur Railway tourne en UTC : on force l'heure locale belge pour
# (a) comparer la clôture des matchs aux date_match (stockés en heure belge)
# et (b) afficher les horodatages. Gère automatiquement CET/CEST (DST).
maintenant_local <- function() format(Sys.time(), "%Y-%m-%d %H:%M", tz = DB_TZ)

fmt_horodatage <- function(x, fmt = "%Y-%m-%d %H:%M") {
  format(as.POSIXct(x), fmt, tz = DB_TZ)
}

# Pseudos disposant des droits d'administration (en plus du flag is_admin en base)
ADMIN_PSEUDOS <- c("thomas")

CREDIT_INITIAL <- 1000
MISE_MIN <- 1
MISE_MAX <- 200

# La finale se joue au meilleur des 3 manches (2 manches gagnantes) : le
# vainqueur l'emporte 2-0 ou 2-1. On parie sur ce score de série.
SCORES_FINALE <- c("2-0", "2-1")

# Opérateur "valeur par défaut" (présent dans R >= 4.4 et rlang, redéfini par sûreté)
`%||%` <- function(a, b) if (is.null(a)) b else a

# ------------------------------------------------------------------
# Placeholders : '?' -> '$1', '$2', ... (RPostgres ne comprend que $n)
# ------------------------------------------------------------------

pg_sql <- function(sql) {
  n <- 0L
  while (grepl("?", sql, fixed = TRUE)) {
    n <- n + 1L
    sql <- sub("?", paste0("$", n), sql, fixed = TRUE)
  }
  sql
}

dbx_exec <- function(con, sql, params = NULL) {
  DBI::dbExecute(con, pg_sql(sql), params = params)
}

dbx_get <- function(con, sql, params = NULL) {
  DBI::dbGetQuery(con, pg_sql(sql), params = params)
}

# ------------------------------------------------------------------
# Connexion : pool de connexions (reconnexion automatique si Railway
# coupe une connexion inactive ; transparent pour le code DBI)
# ------------------------------------------------------------------

parse_db_url <- function(url) {
  # postgres[ql]://user:password@host[:port]/dbname[?options]
  re <- "^postgres(ql)?://([^:]+):([^@]+)@([^:/]+):?([0-9]+)?/([^?]+)"
  m <- regmatches(url, regexec(re, url))[[1]]
  if (length(m) == 0) stop("DATABASE_URL illisible : ", url)
  list(
    user     = utils::URLdecode(m[3]),
    password = utils::URLdecode(m[4]),
    host     = m[5],
    port     = if (m[6] == "") 5432L else as.integer(m[6]),
    dbname   = sub("/$", "", m[7])
  )
}

db_connect <- function() {
  url <- Sys.getenv("DATABASE_URL")
  if (nzchar(url)) {
    p <- parse_db_url(url)
  } else {
    p <- list(
      host     = Sys.getenv("PGHOST", "localhost"),
      port     = as.integer(Sys.getenv("PGPORT", "5432")),
      dbname   = Sys.getenv("PGDATABASE", "kubb"),
      user     = Sys.getenv("PGUSER", "postgres"),
      password = Sys.getenv("PGPASSWORD", "")
    )
  }
  pool::dbPool(
    RPostgres::Postgres(),
    host     = p$host,
    port     = p$port,
    dbname   = p$dbname,
    user     = p$user,
    password = p$password,
    bigint   = "integer",   # COUNT() etc. en integer R plutôt qu'integer64
    timezone = DB_TZ        # timestamps restitués en heure belge
  )
}

db_disconnect <- function(con) {
  pool::poolClose(con)
}

# ------------------------------------------------------------------
# Initialisation du schéma et seed
# ------------------------------------------------------------------

db_init <- function(con, date_debut = next_saturday()) {
  
  dbx_exec(con, "
    CREATE TABLE IF NOT EXISTS meta (version INTEGER NOT NULL)")
  if (dbx_get(con, "SELECT COUNT(*) AS n FROM meta")$n == 0) {
    dbx_exec(con, "INSERT INTO meta (version) VALUES (0)")
  }
  
  dbx_exec(con, "ALTER TABLE meta ADD COLUMN IF NOT EXISTS
               version_matchs INTEGER NOT NULL DEFAULT 0")
  
  dbx_exec(con, "
    CREATE TABLE IF NOT EXISTS users (
      user_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nom        TEXT NOT NULL,
      pseudo     TEXT NOT NULL,
      language   TEXT NOT NULL,
      password   TEXT NOT NULL,
      statcoins  DOUBLE PRECISION NOT NULL DEFAULT 0,  -- crédité via transactions
      is_admin   INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )")
  # Unicité du pseudo insensible à la casse (équivalent du COLLATE NOCASE)
  dbx_exec(con, "
    CREATE UNIQUE INDEX IF NOT EXISTS users_pseudo_lower
    ON users (lower(pseudo))")
  
  dbx_exec(con, "
    CREATE TABLE IF NOT EXISTS teams (
      team_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nom     TEXT NOT NULL UNIQUE
    )")
  
  # date_match reste du TEXT 'YYYY-MM-DD HH:MM' : les comparaisons de
  # chaînes et les substr() des modules fonctionnent à l'identique.
  dbx_exec(con, "
    CREATE TABLE IF NOT EXISTS matches (
      match_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      journee    INTEGER NOT NULL,
      date_match TEXT NOT NULL,
      home_id    INTEGER NOT NULL REFERENCES teams(team_id),
      away_id    INTEGER NOT NULL REFERENCES teams(team_id),
      played     INTEGER NOT NULL DEFAULT 0,
      score_home INTEGER,
      score_away INTEGER
    )")
  
  dbx_exec(con, "
    CREATE TABLE IF NOT EXISTS bets (
      bet_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id   INTEGER NOT NULL REFERENCES users(user_id),
      match_id  INTEGER NOT NULL REFERENCES matches(match_id),
      type      TEXT NOT NULL,             -- 'vainqueur' | 'ecart'
      selection TEXT NOT NULL,             -- team_id (en texte) ou '1-2' / '3-5' / '6'
      mise      DOUBLE PRECISION NOT NULL,
      cote      DOUBLE PRECISION NOT NULL, -- cote figée au moment du pari
      settled   INTEGER NOT NULL DEFAULT 0,
      gain      DOUBLE PRECISION,
      placed_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )")
  
  dbx_exec(con, "
    CREATE TABLE IF NOT EXISTS transactions (
      tx_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES users(user_id),
      montant DOUBLE PRECISION NOT NULL,
      motif   TEXT NOT NULL,
      ts      TIMESTAMPTZ NOT NULL DEFAULT now()
    )")

  # Paris sur le vainqueur du tournoi (champion) + score exact de la finale.
  # Marché indépendant des matchs : les finalistes ne sont pas encore connus,
  # on parie sur n'importe quelle équipe. La mise n'est pas plafonnée (all-in).
  dbx_exec(con, "
    CREATE TABLE IF NOT EXISTS champion_bets (
      bet_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id   INTEGER NOT NULL REFERENCES users(user_id),
      team_id   INTEGER NOT NULL REFERENCES teams(team_id),
      score     TEXT NOT NULL,             -- score de la finale (série), ex. '2-1'
      mise      DOUBLE PRECISION NOT NULL,
      cote      DOUBLE PRECISION NOT NULL, -- cote figée au moment du pari
      settled   INTEGER NOT NULL DEFAULT 0,
      gain      DOUBLE PRECISION,
      placed_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )")

  # Résultat final du tournoi : une seule ligne (id = 1). Tant que settled = 0
  # le marché reste ouvert ; l'admin le clôt en désignant champion + score.
  dbx_exec(con, "
    CREATE TABLE IF NOT EXISTS champion_result (
      id       INTEGER PRIMARY KEY,
      team_id  INTEGER REFERENCES teams(team_id),
      score    TEXT,
      settled  INTEGER NOT NULL DEFAULT 0
    )")
  if (dbx_get(con, "SELECT COUNT(*) AS n FROM champion_result")$n == 0) {
    dbx_exec(con, "INSERT INTO champion_result (id, settled) VALUES (1, 0)")
  }

  # Override manuel de qualification (admin) : force une équipe en lice ou
  # éliminée, en dérogation au calcul automatique. Absence de ligne = auto.
  dbx_exec(con, "
    CREATE TABLE IF NOT EXISTS champion_override (
      team_id INTEGER PRIMARY KEY REFERENCES teams(team_id),
      elimine INTEGER NOT NULL      -- 0 = forcé en lice, 1 = forcé éliminé
    )")
  
  # --- Seed des équipes -------------------------------------------
  if (dbx_get(con, "SELECT COUNT(*) AS n FROM teams")$n == 0) {
    if (file.exists("data/teams.csv")) {
      teams <- readr::read_csv("data/teams.csv", show_col_types = FALSE)
      purrr::walk(teams$nom, function(x) {
        dbx_exec(con, "INSERT INTO teams (nom) VALUES (?)", params = list(x))
      })
    } else {
      defaut <- c(
        "Les B\u00fbcherons", "Kubb Kong", "Viking Social Club",
        "Les Rois Tomb\u00e9s", "Bois Sans Soif", "La Garde Royale",
        "Lancer Franc", "Les Valkubbries"
      )
      purrr::walk(defaut, function(x) {
        dbx_exec(con, "INSERT INTO teams (nom) VALUES (?)", params = list(x))
      })
    }
  }
  
  # --- Seed du calendrier ------------------------------------------
  if (dbx_get(con, "SELECT COUNT(*) AS n FROM matches")$n == 0) {
    if (file.exists("data/matches.csv")) {
      # colonnes attendues : journee, date_match, home (nom), away (nom)
      mt <- readr::read_csv("data/matches.csv", show_col_types = FALSE)
      teams <- dbx_get(con, "SELECT team_id, nom FROM teams")
      mt$home_id <- teams$team_id[match(mt$home, teams$nom)]
      mt$away_id <- teams$team_id[match(mt$away, teams$nom)]
      purrr::pwalk(
        mt[, c("journee", "date_match", "home_id", "away_id")],
        function(journee, date_match, home_id, away_id) {
          dbx_exec(con, "
            INSERT INTO matches (journee, date_match, home_id, away_id)
            VALUES (?, ?, ?, ?)",
                   params = list(journee, as.character(date_match), home_id, away_id))
        }
      )
    } else {
      seed_round_robin(con, date_debut)
    }
  }
  
  invisible(con)
}

next_saturday <- function(from = Sys.Date()) {
  u <- as.integer(format(from, "%u"))  # lundi = 1 ... dimanche = 7
  d <- (6 - u) %% 7
  if (d == 0) d <- 7
  from + d
}

# Calendrier round-robin (méthode du cercle) : 8 équipes, 7 journées,
# 4 matchs par journée, une journée par semaine, matchs à 14h, 15h, 16h, 17h.
seed_round_robin <- function(con, date_debut) {
  ids <- dbx_get(con, "SELECT team_id FROM teams ORDER BY team_id")$team_id
  stopifnot(length(ids) == 8)
  n <- length(ids)
  rotation <- ids[-1]
  
  for (j in seq_len(n - 1)) {
    ligne <- c(ids[1], rotation)
    date_j <- date_debut + (j - 1) * 7
    for (k in seq_len(n / 2)) {
      home <- ligne[k]
      away <- ligne[n + 1 - k]
      heure <- sprintf("%02d:00", 13 + k)  # 14:00 à 17:00
      dbx_exec(con, "
        INSERT INTO matches (journee, date_match, home_id, away_id)
        VALUES (?, ?, ?, ?)",
               params = list(j, paste(format(date_j), heure), home, away))
    }
    rotation <- c(rotation[length(rotation)], rotation[-length(rotation)])
  }
}

# ------------------------------------------------------------------
# Versionnage léger (synchronisation des sessions via reactivePoll)
# ------------------------------------------------------------------

db_touch <- function(con) {
  dbx_exec(con, "UPDATE meta SET version = version + 1")
}

# db_version <- function(con) {
#   dbx_get(con, "SELECT version FROM meta")$version[1]
# }

db_touch_matchs <- function(con) {
  dbx_exec(con, "UPDATE meta SET version = version + 1,
                                 version_matchs = version_matchs + 1")
}
db_versions <- function(con) {
  dbx_get(con, "SELECT version, version_matchs FROM meta")
}

# ------------------------------------------------------------------
# Helpers de lecture
# ------------------------------------------------------------------

get_user <- function(con, user_id) {
  dbx_get(con, "SELECT * FROM users WHERE user_id = ?",
          params = list(user_id))
}

get_user_by_pseudo <- function(con, pseudo) {
  dbx_get(con, "SELECT * FROM users WHERE lower(pseudo) = lower(?)",
          params = list(pseudo))
}

get_teams <- function(con) {
  dbx_get(con, "SELECT * FROM teams ORDER BY nom")
}

get_matches <- function(con) {
  dbx_get(con, "
    SELECT m.*, th.nom AS home, ta.nom AS away
    FROM matches m
    JOIN teams th ON th.team_id = m.home_id
    JOIN teams ta ON ta.team_id = m.away_id
    ORDER BY m.journee, m.date_match, m.match_id")
}

get_bets <- function(con, user_id = NULL) {
  base <- "
    SELECT b.*, u.pseudo, m.journee, m.date_match, m.home_id, m.away_id,
           th.nom AS home, ta.nom AS away
    FROM bets b
    JOIN users u   ON u.user_id  = b.user_id
    JOIN matches m ON m.match_id = b.match_id
    JOIN teams th  ON th.team_id = m.home_id
    JOIN teams ta  ON ta.team_id = m.away_id"
  if (is.null(user_id)) {
    dbx_get(con, paste(base, "ORDER BY b.placed_at DESC"))
  } else {
    dbx_get(con, paste(base, "WHERE b.user_id = ? ORDER BY b.placed_at DESC"),
            params = list(user_id))
  }
}

# --- Paris sur le champion du tournoi ---------------------------------

get_champion_bets <- function(con, user_id = NULL) {
  base <- "
    SELECT b.*, u.pseudo, t.nom AS equipe
    FROM champion_bets b
    JOIN users u ON u.user_id = b.user_id
    JOIN teams t ON t.team_id = b.team_id"
  if (is.null(user_id)) {
    dbx_get(con, paste(base, "ORDER BY b.placed_at DESC"))
  } else {
    dbx_get(con, paste(base, "WHERE b.user_id = ? ORDER BY b.placed_at DESC"),
            params = list(user_id))
  }
}

# Résultat final du tournoi (1 ligne). champion_ouvert() : marché encore ouvert.
get_champion_result <- function(con) {
  r <- dbx_get(con, "SELECT * FROM champion_result WHERE id = 1")
  if (nrow(r) == 0) return(list(settled = 0, team_id = NA, score = NA))
  as.list(r)
}

champion_ouvert <- function(con) {
  get_champion_result(con)$settled == 0
}

# Overrides manuels de qualification : vecteur nommé team_id -> 0/1 (vide si
# aucun). 0 = forcé en lice, 1 = forcé éliminé.
get_elim_overrides <- function(con) {
  r <- dbx_get(con, "SELECT team_id, elimine FROM champion_override")
  if (nrow(r) == 0) return(setNames(integer(0), character(0)))
  setNames(as.integer(r$elimine), as.character(r$team_id))
}

# Fixe (ou retire) l'override d'une équipe. statut : "auto" (retire),
# "lice" (forcé en lice) ou "elim" (forcé éliminé). Bascule version_matchs
# pour invalider le cache des pronostics et des cotes.
set_elim_override <- function(con, team_id, statut) {
  team_id <- as.integer(team_id)
  if (identical(statut, "auto")) {
    dbx_exec(con, "DELETE FROM champion_override WHERE team_id = ?",
             params = list(team_id))
  } else {
    val <- if (identical(statut, "elim")) 1L else 0L
    dbx_exec(con, "
      INSERT INTO champion_override (team_id, elimine) VALUES (?, ?)
      ON CONFLICT (team_id) DO UPDATE SET elimine = EXCLUDED.elimine",
             params = list(team_id, val))
  }
  db_touch_matchs(con)
}

get_transactions <- function(con) {
  dbx_get(con, "
    SELECT t.*, u.pseudo
    FROM transactions t
    JOIN users u ON u.user_id = t.user_id
    ORDER BY t.ts, t.tx_id")
}

# ------------------------------------------------------------------
# Écriture : toute variation de StatCoins passe par le grand livre
# ------------------------------------------------------------------

add_transaction <- function(con, user_id, montant, motif) {
  dbx_exec(con, "
    INSERT INTO transactions (user_id, montant, motif) VALUES (?, ?, ?)",
           params = list(user_id, montant, motif))
  dbx_exec(con, "
    UPDATE users SET statcoins = statcoins + ? WHERE user_id = ?",
           params = list(montant, user_id))
}

# Placement atomique d'un pari sur le champion : débit du solde, insertion
# du pari, écriture au grand livre et bascule de version en une transaction
# (CTE). Le garde-fou statcoins >= mise interdit tout solde négatif, même en
# all-in. Renvoie le bet_id créé, ou un data.frame vide si solde insuffisant.
place_champion_bet <- function(con, user_id, team_id, score, mise, cote) {
  dbx_get(con, "
    WITH u AS (
      UPDATE users SET statcoins = statcoins - ?::double precision
      WHERE user_id = ?::int AND statcoins >= ?::double precision
      RETURNING user_id
    ), b AS (
      INSERT INTO champion_bets (user_id, team_id, score, mise, cote)
      SELECT user_id, ?::int, ?::text, ?::double precision, ?::double precision
      FROM u
      RETURNING bet_id
    ), t AS (
      INSERT INTO transactions (user_id, montant, motif)
      SELECT user_id, ?::double precision, ?::text FROM u
    ), v AS (
      UPDATE meta SET version = version + 1 WHERE EXISTS (SELECT 1 FROM u)
    )
    SELECT bet_id FROM b",
    params = list(mise, user_id, mise,
                  team_id, score, mise, unname(cote),
                  -mise, "Mise sur le champion du tournoi"))
}

# ------------------------------------------------------------------
# Annulation de paris (admin) : rembourse la mise, trace dans le grand
# livre, supprime le pari. Atomique par pari (CTE), et restreint aux
# paris NON réglés (settled = 0) : on ne touche jamais à un match déjà
# joué. Les bet_id déjà réglés ou inexistants sont silencieusement
# ignorés (le garde-fou SQL empêche tout double remboursement, même si
# la sélection de l'admin était périmée).
# ------------------------------------------------------------------

annuler_paris <- function(con, bet_ids) {
  bet_ids <- unique(as.integer(bet_ids))
  bet_ids <- bet_ids[!is.na(bet_ids)]
  
  n_ok <- 0L
  total_rendu <- 0
  
  for (bid in bet_ids) {
    res <- dbx_get(con, "
      WITH d AS (
        DELETE FROM bets
        WHERE bet_id = ? AND settled = 0
        RETURNING bet_id, user_id, mise
      ), u AS (
        UPDATE users SET statcoins = statcoins + (SELECT mise FROM d)
        WHERE user_id = (SELECT user_id FROM d)
        RETURNING user_id
      ), t AS (
        INSERT INTO transactions (user_id, montant, motif)
        SELECT user_id, mise,
               '[Admin] Annulation du pari #' || bet_id::text
        FROM d
      )
      SELECT mise FROM d",
                   params = list(bid))
    
    if (nrow(res) == 1) {
      n_ok <- n_ok + 1L
      total_rendu <- total_rendu + res$mise[1]
    }
  }
  
  # Une seule bascule de version : réveille les sessions (solde + tables)
  if (n_ok > 0) db_touch(con)

  list(n_annules = n_ok,
       total_rendu = total_rendu,
       n_ignores = length(bet_ids) - n_ok)
}

# ------------------------------------------------------------------
# Annulation de paris sur le champion (admin) : même principe que
# annuler_paris(), mais sur la table champion_bets. Restreint aux paris
# non réglés (settled = 0) : une fois le champion désigné, plus rien à
# annuler. Atomique par pari, remboursement tracé au grand livre.
# ------------------------------------------------------------------

annuler_paris_champion <- function(con, bet_ids) {
  bet_ids <- unique(as.integer(bet_ids))
  bet_ids <- bet_ids[!is.na(bet_ids)]

  n_ok <- 0L
  total_rendu <- 0

  for (bid in bet_ids) {
    res <- dbx_get(con, "
      WITH d AS (
        DELETE FROM champion_bets
        WHERE bet_id = ? AND settled = 0
        RETURNING bet_id, user_id, mise
      ), u AS (
        UPDATE users SET statcoins = statcoins + (SELECT mise FROM d)
        WHERE user_id = (SELECT user_id FROM d)
        RETURNING user_id
      ), t AS (
        INSERT INTO transactions (user_id, montant, motif)
        SELECT user_id, mise,
               '[Admin] Annulation du pari champion #' || bet_id::text
        FROM d
      )
      SELECT mise FROM d",
                   params = list(bid))

    if (nrow(res) == 1) {
      n_ok <- n_ok + 1L
      total_rendu <- total_rendu + res$mise[1]
    }
  }

  if (n_ok > 0) db_touch(con)

  list(n_annules = n_ok,
       total_rendu = total_rendu,
       n_ignores = length(bet_ids) - n_ok)
}